getwd()
data()
help(trees)
str(trees)
class(trees$Height)
print(trees$Height)
table(trees$Height)
min(trees$Girth)
min(trees$Height)
min(trees$Volume)
#apply(table, row1/col2, func)
apply(trees, 1, max)
nrow(trees)
ncol(trees)
names(trees)
dim(trees)
data(iris)
?summary(trees)
range

data(iris)
help(iris)
names(iris)
print(iris)
summary(iris)
apply(iris, 2, max)

idata = read.csv("./data.csv")
apply(idata, 2, sum)
names(idata)
summary(idata)
nrow(idata)
ncol(idata)
dim(idata)
range(idata$price)
is.na(idata)
mean(idata$price, na.rm="F")

help(MASS)
library(MASS)
help(survey)
mean(survey$NW.Hnd, na.rm="T")
hist(survey$Wr.Hnd)
boxplot(split(survey$Height, survey$Sex))

