#!/bin/sh
if [ $# -eq 0 ]:
then
	echo "USAGE: $0 <file>"
	exit
fi
g++ $1.cpp -o $1 -pass-exit-codes
if [ $? -eq 0 ]:
then
	echo "Compiled Successfully"
	printf "\nRun this Program?(y/n):"
	read us
	us=`echo $us | tr [Y] [y]`
	if [ $us = 'y' ]:
	then
		$1
	fi
	
fi
printf "\nDo you want to Clear and Continue?(y/n)[r for retry]:"
read us
us=`echo $us | tr [Y] [y]`
if [ $us = 'y' ]:
then
	clear
fi
if [ $us = 'r' ]:
then
	c $1
fi
if [ $us = 'cr' ]:
then
	tput clear
	c $1
fi